#!/usr/bin/env python3
"""sync_codex_profiles.py — 从 cc-switch 数据库导出 codex provider 配置，
生成 ~/.codex/<profile>.config.toml 覆盖层，供 Reasonix 编排控制台按节点路由
（run: `codex --profile <name>`；serve: app-server `-c key=value` 覆盖）。

映射（框架 codexProfile 识别）：
  - provider 名含 "deepseek"          -> ~/.codex/deepseek.config.toml（官方直连）
  - provider 名含 "right code" 且模型 gpt-* -> ~/.codex/ccs.config.toml（中转站 gpt）
  - 其余 codex provider 打印信息，可手动扩展映射表

用法：
  python scripts/sync_codex_profiles.py
"""
import json, os, re, sqlite3, sys

DB = os.path.expanduser("~/.cc-switch/cc-switch.db")
CODEX_HOME = os.environ.get("CODEX_HOME") or os.path.expanduser("~/.codex")


def pick_token(auth: dict) -> str:
    for k, v in auth.items():
        if isinstance(v, str) and v.startswith("sk-"):
            return v
    return ""


def generate_toml(name: str, model: str, base_url: str, token: str) -> str:
    return f"""# Codex profile overlay: {name}
# Generated by scripts/sync_codex_profiles.py from cc-switch provider "{name}".
# Self-contained: explicit bearer token; independent of global config.toml /
# auth.json which cc-switch rewrites when switching providers.
model_provider = "custom"
model = "{model}"

[model_providers.custom]
name = "{name}"
base_url = "{base_url}"
wire_api = "responses"
requires_openai_auth = false
experimental_bearer_token = "{token}"
"""


def main() -> int:
    if not os.path.exists(DB):
        print(f"[sync-codex-profiles] cc-switch db not found: {DB}")
        return 1
    con = sqlite3.connect(DB)
    cur = con.cursor()
    rows = cur.execute(
        "SELECT id, name, settings_config FROM providers WHERE app_type='codex'"
    ).fetchall()
    con.close()

    written = []
    for pid, name, settings in rows:
        try:
            j = json.loads(settings)
        except Exception:
            continue
        conf = j.get("config", "") or ""
        auth = j.get("auth", {}) or {}
        m_model = re.search(r'(?m)^model\s*=\s*"([^"]+)"', conf)
        m_url = re.search(r'(?m)^base_url\s*=\s*"([^"]+)"', conf)
        model = m_model.group(1) if m_model else ""
        base_url = m_url.group(1) if m_url else ""
        token = pick_token(auth)

        lower = name.lower()
        if "deepseek" in lower:
            out = os.path.join(CODEX_HOME, "deepseek.config.toml")
            with open(out, "w", encoding="utf-8", newline="\n") as f:
                f.write(generate_toml(name, model, base_url, token))
            written.append(f"{out}  (deepseek, model={model})")
        elif "right code" in lower and model.startswith("gpt"):
            out = os.path.join(CODEX_HOME, "ccs.config.toml")
            with open(out, "w", encoding="utf-8", newline="\n") as f:
                f.write(generate_toml(name, model, base_url, token))
            written.append(f"{out}  (ccs/right-code, model={model})")
        else:
            print(f"[sync-codex-profiles] skip provider: {name} (model={model}, base_url={base_url})")

    for w in written:
        print(f"[sync-codex-profiles] wrote {w}")
    if not written:
        print("[sync-codex-profiles] no deepseek/right-code provider found; nothing written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
